### ISSUE TITLE
details

### ISSUE THREAD

**Issue by vmazataud** [fcingolani/wordpress-juxtapose#1]
Hi There and thanks for this, 

I am trying to use you plugin.
It's installed and activated on my wordpress WordPress 4.1.2
But then I don't understand, do I have to mix the iframe from Juxtapose website and your code ?
Should the image be on my website or those I uploaded on the Juxtapose site.
If you can help with this, that would be great
Thanks
Val

**Comment by fcingolani** [comment]
Hi!

I would recommend to upload the files to your own WordPress. I've written some quick tutorial, hope it helps:

## 1. Get image URLs

You can get both image URLs from your WP Media Library:

![wp1](https://cloud.githubusercontent.com/assets/420163/7289471/15f43acc-e947-11e4-9510-3eca21f563e5.PNG)

## 2. Write a Juxtapose shortcode

Having both URLs, i.e.:
- http://localhost/wordpress/wp-content/uploads/2015/03/Hydrangeas.jpg
- http://localhost/wordpress/wp-content/uploads/2015/03/Desert.jpg

... you write a <code>juxtapose</code> shortcode in the Post WYSIWYG editor:

```
[juxtapose leftsrc="http://localhost/wordpress/wp-content/uploads/2015/03/Hydrangeas.jpg" rightsrc="http://localhost/wordpress/wp-content/uploads/2015/03/Desert.jpg"]
```

![w2](https://cloud.githubusercontent.com/assets/420163/7289605/c4aa2314-e948-11e4-9ff9-1dbe0cf21602.PNG)

## 3. Publish and enjoy

![w3](https://cloud.githubusercontent.com/assets/420163/7289675/b002f976-e949-11e4-9877-a5b39410af7f.gif)

:smiley:

**Comment by vmazataud** [comment]
thanks for that, I will try it !
