### ISSUE TITLE
Installation 

### ISSUE THREAD

**Issue by mdelrue** [fcingolani/wordpress-juxtapose#2]
Hi ! 

I would like to instal your plug-in on my wordpress (mdelrue.be) but, as I'm not a professional, I don't know how to proceed. I don't find your plug-in online and I can't find a zip file asked by wordpress either. 

Thanks a lot,

Max

**Comment by fcingolani** [comment]
Hi Max,

You can download the plugin [directly from GitHub as a .zip](https://github.com/fcingolani/wordpress-juxtapose/archive/master.zip) file. Then just upload it to your WordPress blog using the [Upload tab in the Add Plugins screen](https://codex.wordpress.org/Plugins_Add_New_Screen#Upload_Tab).

I've added this information to the README file too.

Let me know how it goes!

Federico

**Comment by mdelrue** [comment]
![capture d ecran 2015-05-31 a 10 54 11](https://cloud.githubusercontent.com/assets/12674639/7901343/6c577e56-0783-11e5-9fff-10efad007546.png)

Perfect ! It's working ! Thanks a lot ! 

Do you know why I don't the right arrow at the middle of the slider ?
Further more, I suppose I can add a label by adding "right/leftcredit" after the src element ?

Thanks again, your plugin is really helpful !

**Comment by fcingolani** [comment]
Mmm i couldn't tell why the right arrow does not appear. It may be something about your CSS styles or some issue with JuxtaposeJS itself. This plugin is just a tool to generate the embed code without admin privileges or editing your theme, the .js and .css files are loaded from Knightlab's own CDN, so they are out of my control.

About the labels, you could use something like:

```
[juxtapose leftsrc="http://localhost/wordpress/wp-content/uploads/2015/03/Hydrangeas.jpg" leftlabel="Hydrangeas" rightsrc="http://localhost/wordpress/wp-content/uploads/2015/03/Desert.jpg" rightlabel="Desert"]
```

I wouldn't recommend using rightcredit and leftcredit, as they are awfully presented below the slider. I think labels look better. Personal taste.

**Comment by mdelrue** [comment]
Perfect ! Thanks a lot !

Maxime DELRUE
@mdelrue

2015-05-31 22:59 GMT+02:00 Federico Cingolani notifications@github.com:
